### PR TITLE
refactor: prefer `URL`

### LINKED ISSUE #4: Build failed on Windows
Hi there!
I really like this work, but I've got small problem:

Build failed on Windows with the following error message:
`Error: ENOENT: no such file or directory, lstat 'C:\C:\Users\hoqn\...\src\pages'`

### LINKED ISSUE #5: ENOENT: no such file or directory, lstat /src/pages
When I try to build a project, I get this error.

### PR DESCRIPTION
**Pull request by lemueldls**
Fixes #4
Fixes #5

### CODE REVIEW

**Comment by jlarmstrongiv** [comment]
Hey @lemueldls thanks for the PR!  If it solves the errors people seem to be running into, I’ll merge it. 

Can you reproduce either of the issues you linked #4 and #5?  My demo builds successfully on all platforms.  I need to see an example that causes those errors on windows (or whichever platform has those errors).

The `node:path` module specifically provides `path.join`, `path.normalize`, and `path.resolve` to ensure that paths work cross platform.  Would you explain how preferring `URL` would solve those issues above?

On windows:
```
> path.join('awkward/use/of\\slashes', '\in/this/path')
'awkward\\use\\of\\slashes\\in\\this\\path'
> path.normalize(path.join('awkward/use/of\\slashes', '\in/this/path'))
'awkward\\use\\of\\slashes\\in\\this\\path'
> path.normalize('awkward/use/of\\slashes')
'awkward\\use\\of\\slashes'
> path.resolve(path.normalize(path.join('awkward/use/of\\slashes', '\in/this/path')))
'C:\\Users\\username\\source\\repos\\TryAstroBug\\node-v18.16.1-win-x64\\awkward\\use\\of\\slashes\\in\\this\\path'
```

On mac (`\\` is valid in unix):
```
> path.join('awkward/use/of\\slashes', '\in/this/path')
'awkward/use/of\\slashes/in/this/path'
> path.normalize(path.join('awkward/use/of\\slashes', '\in/this/path'))
'awkward/use/of\\slashes/in/this/path'
> path.normalize('awkward/use/of\\slashes')
'awkward/use/of\\slashes'
> path.resolve(path.normalize(path.join('awkward/use/of\\slashes', '\in/this/path')))
'/Users/username/awkward/use/of\\slashes/in/this/path'
```

On Linux (also unix): 
```
> path.join('awkward/use/of\\slashes', '\in/this/path')
'awkward/use/of\\slashes/in/this/path'
> path.normalize(path.join('awkward/use/of\\slashes', '\in/this/path'))
'awkward/use/of\\slashes/in/this/path'
> path.normalize('awkward/use/of\\slashes')
'awkward/use/of\\slashes'
> path.resolve(path.normalize(path.join('awkward/use/of\\slashes', '\in/this/path')))
'/mnt/c/Users/username/awkward/use/of\\slashes/in/this/path'
```

**Comment by lemueldls** [comment]
Sure! I have a CI build on a project I'm working on with the failing build here:
https://github.com/Kaetram/Kaetram-Open/actions/runs/5471594889/jobs/9962891191

Astro's `config.srcDir` is already a `URL`, and uses forward slashes over backslashes on Windows. This causes a problem with windows drive paths, `C:/`, having a leading slash, `/C:/`, when using `url.pathname`. Also causing it to interpret `/C:/` as `C:\C:\`, hence #4.

Using `fileURLToPath` solves that issue in particular as shown in this quick REPL in PowerShell:
```js
PS C:\Users\Lemuel> node
Welcome to Node.js v20.3.1.
Type ".help" for more information.
> const path = require("node:path")
undefined
> const { fileURLToPath } = require("node:url");
undefined
> const home = new URL("file://C:/Users/Lemuel/");
undefined
> home.pathname;
'/C:/Users/Lemuel/'
> path.normalize(home.pathname);
'\\C:\\Users\\Lemuel\\'
> fileURLToPath(home);
'C:\\Users\\Lemuel\\'
> const documents = new URL("./Documents", home);
undefined
> fileURLToPath(documents);
'C:\\Users\\Lemuel\\Documents'
```

Using `path.normalize` only makes it interpret the leading slash into backslashes.

While removing the leading slash on only Windows platform could also be a solution, making a few other variables `URL` over just strings was for convenience when using `config.srcDir`.

Most if not all of `node:fs` also support passing in `URL`s, and are much easier to work with when on ESM, when `__filename` and `__dirname` aren't available.

**Comment by jlarmstrongiv** [comment]
@hoqn, @lemueldls, @tiwka19 thank you all for your help.  This windows bug has been fixed in `0.0.18`.

@lemueldls thank you for your reproducible example to test against and other refactors, which were added
@hoqn thank you for pointing out `removeLeadingForwardSlashWindows` in the astro [source code](https://github.com/withastro/astro/blob/864291212036819df9c3e5ad2dee5d921c1bdec8/packages/internal-helpers/src/path.ts#L26)

This fix would not have been possible without all of your help 🚀 really appreciate it

**Comment by lemueldls** [comment]
Ah, one more thing!

Use `fg.convertPathToPattern` in the `ensurePathsHaveConfigSrcDirPathname` function, or no paths with be resolved on windows!

**Comment by jlarmstrongiv** [comment]
I meant fixed in `0.0.19` 😂 thanks again @lemueldls

**Comment by lemueldls** [comment]
Last one I swear, this one's my bad 😬

`convertPathToPattern` was added in `fast-glob` 3.3.0, a quick upgrade

**Comment by jlarmstrongiv** [comment]
Did I say `0.0.19`?  I meant `0.0.20` 😂 another great catch @lemueldls completely missed that one

That is something that I’ve been thinking about.  In application code, I always pin my dependencies to the latest version, whereas in my recent public libraries like this one, I have kept a [range](https://docs.renovatebot.com/dependency-pinning/#ranges-for-libraries) available.  I wonder if there’s a better way to handle that.

**Comment by lemueldls** [comment]
Okay, okay.
https://github.com/Kaetram/Kaetram-Open/actions/runs/5483205878/jobs/9989289488

Hold on you changed a couple of things, lemme see...

**Comment by lemueldls** [comment]
So now, there's a difference in backslashes vs forward slashes, meaning `relativePath` isn't being parsed as expected:

```json
{
  pagesPath: 'C:\\Users\\Lemuel\\Projects\\Kaetram-Open\\packages\\client\\src\\pages',
  relativePath: 'C:/Users/Lemuel/Projects/Kaetram-Open/packages/client/src/pages'
}
```

It should be normalizing through something like `path.relative`, which is why `relativePath` should like this:

```ts
const relativePath = path.relative(pagesPath, parsedPath.dir);
```

And ALSO, also, I added `.replaceAll("\\", "/")` on `pattern` because `injectRoute` does not like backslashes.

I should've explained more of the changes lol, I thought it'd be merged as is.

**Comment by jlarmstrongiv** [comment]
@lemueldls alrighty, try `0.0.21` 😄 no worries, we’ve both learned a lot

**Comment by lemueldls** [comment]
and it works 🎉

**Comment by jlarmstrongiv** [comment]
@lemueldls actually, are you sure `fg.convertPathToPattern` is needed?  It is supposed to accept patterns, not paths actually

**Pull request closed without merging**
